### ISSUE TITLE
agregar semáforo de que el ultimo dato seleccionado esta cerca del umbral

### ISSUE THREAD

**Issue by jbkunst** [FONDEF-ID21-10297/plataforma#4]
@jbkunst  incorporará semáforo
@frzambra dará niveles para determinar valor del semáforo
Indicar cuanto tiempo regar.

**Comment by mherreradiaz** [comment]
Hola @jbkunst, 

Subí un archivo: <data/umbral_tlp.rds> que contiene los umbrales para el semáforo. Lo valores a usar son u_minimo, u_medio y u_maximo. Usando todos los valores de TLP (incluyendo todos los tratamientos por sitio) calculé los valores de la siguiente forma:

u_minimo = min + IQR 
u_medio = min
u_maximo = Q3

Siendo el min el valor mínimo registrado. Estos fueron los valores obtenidos:

  sitio        u_minimo u_medio u_maximo
  <chr>           <dbl>   <dbl>    <dbl>
1 la_esperanza    -1.80   -2.18    -2.35
2 rio_claro       -1.53   -1.86    -2.05

Respecto al semáforo, la idea es que los colores vayan de la siguiente forma:

Verde = ]Inf; u_minimo[
Amarillo/Naranjo = [u_minimo;u_medio[
Rojo (nivel más crítico) = [u_maximo,-Inf[

@frzambra Te parece bien?

Saludos.

**Comment by mherreradiaz** [comment]
> Hola @jbkunst,
> 
> Subí un archivo: <data/umbral_tlp.rds> que contiene los umbrales para el semáforo. Lo valores a usar son u_minimo, u_medio y u_maximo. Usando todos los valores de TLP (incluyendo todos los tratamientos por sitio) calculé los valores de la siguiente forma:
> 
> u_minimo = min + IQR u_medio = min u_maximo = Q3
> 
> Siendo el min el valor mínimo registrado. Estos fueron los valores obtenidos:
> 
> sitio u_minimo u_medio u_maximo 1 la_esperanza -1.80 -2.18 -2.35 2 rio_claro -1.53 -1.86 -2.05
> 
> Respecto al semáforo, la idea es que los colores vayan de la siguiente forma:
> 
> Verde = ]Inf; u_minimo[ Amarillo/Naranjo = [u_minimo;u_medio[ Rojo (nivel más crítico) = [u_maximo,-Inf[
> 
> @frzambra Te parece bien?
> 
> Saludos.

La idea es que esta clasificación se muestre tanto en el layer del estrés como en el gráfico de serie temporal. En la gráfico, las líneas que marcan los umbrales podrían verse por detrás de los demás datos, y todo el área que encierran coloreada según el color que corresponda.
