### ISSUE TITLE
Dejar periodo determinado de una semana y cambiar ajuste del periodo a calendario

### ISSUE THREAD

**Issue by mherreradiaz** [FONDEF-ID21-10297/plataforma#6]
@jbkunst 

El día por defecto en el calendario debería ser el día actual, y la serie temporal debería ser de una semana para atrás del día seleccionado en el calendario sin posibilidad de modificar.

**Comment by jbkunst** [comment]
Pregunta @mherreradiaz , y si no hay datos de en el rds de clima y el de potencial? no muestro nada? se dice que no hay datos?

**Comment by mherreradiaz** [comment]
> Pregunta @mherreradiaz , y si no hay datos de en el rds de clima y el de potencial? no muestro nada? se dice que no hay datos?

Me equivoqué, voy a aclarar. El día por defecto debiese ser el último día de la temporada pasada, o el último día donde hayan datos.
