### ISSUE TITLE
Propuestas para reunión

### ISSUE THREAD

**Issue by mherreradiaz** [FONDEF-ID21-10297/plataforma#7]
@jbkunst 
@frzambra 

- Con @frzambra hablamos este miércoles y nos surgió la idea de dejar solo dos capas para visualizar. En vez de shape y raster, que sean dos shapes: (1) el promedio del potencial en cada sector de riego (sería el que ya está puesto), y (2) el color que corresponda de semáforo en cada sector de riego. A la primera la podríamos llamar directamente "Potencial", y a la segunda "Nivel de estrés", "Estrés" o algo por el estilo.

**Comment by jbkunst** [comment]
Ok, entiendo de lo que tu

**Comment by mherreradiaz** [comment]
> @mherreradiaz Ok, entiendo entonces que en lugar de dar las opciones "shape/raster" se muestre "potencial/estres". (Es decir, los datos raster solamente se utilizarán internamente para obtener el valor del potencial por sector)

Exacto

**Comment by frzambra** [comment]
$\Psi$ Símbolo de potencial

**Comment by jbkunst** [comment]
1. Layer, parte de Abel/Francisco.
2. Gráfico de potencial: mostrar al inicio el de menor potencial, ocultando el resto. El usuario puede mostrarlos haciendo clic.
3. Se agregará un botón de Mostrar detalles que despliegue un modal con una tabla de información.
4. Variables meteorológicas con más tiempo a la sección "temporada".
5. Unificar el gráfico de potencial con el de riego y las variables meteorológicas, compartiendo el eje X (fecha). Revisar los datos de riego.
6. GitHub Actions: @mherreradiaz creará el repositorio, organizará los scripts y añadirá el modelo.

Otros

1. Agregar botón para ir a la fecha actual.

**Comment by mherreradiaz** [comment]
Propuestas reunión Viernes 8/11

- Agregar pestaña de riego al resumen de la semana (lamina acum. ETo, ETc, el local).
- Que se acople la app en la página web.
- Pones solo cuánto se debería regar en el panel.

**Comment by mherreradiaz** [comment]
Pendientes:

- @frzambra  recortar de los datos raster de potencial de acuerdo al poligono del huerto.
- @mherreradiaz  subir el script para ver la lamina de riego acumulada.
- @mherreradiaz subir el scrip para comenzar a trabajar el automatizado del modelo
- @jbkunst acoplar aplicacion satori al sito web
- Analizar la propuesta de Angel

**Comment by frzambra** [comment]
Ver la pisibilidad de incorporar la interacción con el mapa. Es decir, que al hacer clic en un sector de riego, cambien los gŕaficos.

**Comment by frzambra** [comment]
:+1:
